global_args:
  trainer_backend: pl
  enable_deepspeed: false
  enable_ptv2: false
  enable_lora: true
  load_in_bit: 0
  config_merge: {}
  # 模型权重 ， 对应 config.constant_map.py
  model_name: Baichuan2-7B-Chat

  # one of auto 16 bf16 32
  precision: auto
  quantization_config:
    load_in_8bit: false
    load_in_4bit: false
    llm_int8_threshold: 6.0
    llm_int8_has_fp16_weight: false
    bnb_4bit_compute_dtype: float16  # one of float16  bfloat16 float32
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4


global_models_mapper: 
    # 第二代模型
    Baichuan2-7B-Base: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan2/Baichuan2-7B-Base
        config_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-7B-Base/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-7B-Base
    
    Baichuan2-7B-Chat: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan2/Baichuan2-7B-Chat
        config_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-7B-Chat/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-7B-Chat
    

    Baichuan2-13B-Base: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan2/Baichuan2-13B-Base
        config_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-13B-Base/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-13B-Base
    
    Baichuan2-13B-Chat: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan2/Baichuan2-13B-Chat
        config_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-13B-Chat/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan2/Baichuan2-13B-Chat
    

    baichuan2-7b-chat-int4: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan2/baichuan2-7b-chat-int4
        config_name: /data/nlp/pre_models/torch/baichuan2/baichuan2-7b-chat-int4/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan2/baichuan2-7b-chat-int4
    

    baichuan2-13b-chat-int4: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan2/baichuan2-13b-chat-int4
        config_name: /data/nlp/pre_models/torch/baichuan2/baichuan2-13b-chat-int4/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan2/baichuan2-13b-chat-int4
    

    # 第一代

    Baichuan-13B-Base: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Base
        config_name: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Base/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Base
    
    Baichuan-13B-Chat: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Chat
        config_name: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Chat/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Chat
    
    baichuan-13b-chat-int4: 
        model_type: baichuan
        model_name_or_path: /data/nlp/pre_models/torch/baichuan/baichuan-13b-chat-int4
        config_name: /data/nlp/pre_models/torch/baichuan/baichuan-13b-chat-int4/config.json
        tokenizer_name: /data/nlp/pre_models/torch/baichuan/baichuan-13b-chat-int4
